[package]
name = "cyber-dao-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.cyber-dao]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
